```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width=8, fig.height = 6)

library(tidyverse)
library(ggplot2)
library(grid)
library(readxl)
library(metafor)

source('../../helper_functions.R')
```

```{r}
pct_change_df <- read_excel("effect_sizes.xlsx") %>%
  filter(include_in_meta == TRUE, point_estimate_unit == "Percent Change")

# note: because there are so few studies in each category, the actual meta-analysis results are not interpretable! I'm just using {rma} so that I can plot the effect sizes using a forest plot
pct_change_meta <- rma(yi = 100 * point_estimate, sei = 100 * standard_error, data=pct_change_df)

forest(pct_change_meta, slab = study, psize=1, header="Study")
grid.text("OSHA Inspections Reduce Workplace Injuries by ~9%", 0.46, 0.9, gp=gpar(cex=1.5))
mtext("Workplace injuries are defined as those resulting in employees missing work (Johnson, Levine,and Toffel 2023)\nor a worker's compensation claim (Levine, Toffel, and Johnson 2012).", side=1, line=4, cex=0.8, adj=0)
```


```{r}
abs_diff_df <- read_excel("effect_sizes.xlsx") %>%
  filter(include_in_meta == TRUE, point_estimate_unit == "Absolute Difference")

# note: because there are so few studies in each category, the actual meta-analysis results are not interpretable! I'm just using {rma} so that I can plot the effect sizes using a forest plot
abs_diff_meta <- rma(yi = point_estimate, sei = standard_error, data=abs_diff_df)

forest(abs_diff_meta, slab = study, ilab=cbind(control_avg), ilab.lab=c("Baseline"), header = "Study", 
       rows = c(3:4, 8:8), psize = 1, ylim = c(-2, 12))
 
### set font expansion factor (as in forest() above)
op <- par(cex=0.75)

 
### add text for the subgroups
text(-14, c(5, 9), pos=4, c("DART Rate (Per 100 Full-Time Employees)", "Fatality Rate (Per 10,000 Employees)"), font=4, cex = 1.2)
 
### set par back to the original settings
par(op)

grid.text("OSHA Inspections Reduce Workplace Fatalities and Injuries", 0.49, 0.9, gp=gpar(cex=1.5))
mtext("The DART rate is defined as the # of workplace injuries/illnesses causing employees to miss work, be placed\non restricted duties, or be transferred to another job site per 100 full-time employees.", side=1, line=4, cex=0.8, adj=0)
```

```{r}
budget_df <- read_excel("budget_allocation_fy2025.xlsx")

sources <- c("FY 2025 Congressional Budget Justification, OSHA")
notes <- c("Inspections are formally described as 'Federal Enforcement'", "Compliance assistance represents a combination of assistance at the federal level, state level, and training grants.")
caption <- create_caption(sources, notes)

ggplot(budget_df, aes(x = reorder(budget_category, budget_dollar_amount), y = budget_dollar_amount / 1000000))+
  geom_bar(stat = "identity")+
  labs(x = "Category", y = "FY2025 Budget Request", title = "Workplace Safety Inspections Made Up ~40% of OSHA's Budget \nThis Year", caption = caption)+
  scale_y_continuous(labels = scales::dollar_format(prefix="$", suffix = "M"))+
  coord_flip()+
  theme_minimal()+
  theme(plot.caption.position = 'plot', plot.caption = element_text(hjust = 0))
```